title: GitHub Copilot Toolkit
description: Recommended links, skills, agentic workflows & settings for GitHub Copilot
remote_theme: just-the-docs/just-the-docs@v0.10.1

url: "https://theomonfort.github.io"
baseurl: "/theomonfort"

color_scheme: dark

aux_links: {}

nav_external_links: []

heading_anchors: true
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Built with <a href=\"https://github.com/just-the-docs/just-the-docs\">Just the Docs</a> · <a href=\"https://github.com/theomonfort\">@theomonfort</a>"

exclude:
  - .github/
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
